import { describe, expect, it, vi } from 'vitest'
import { createCentralEditorStore } from '../src/client/central-editor-state.ts'

function selectedStore() {
  const store = createCentralEditorStore()
  store.setSession('a')
  return store
}

describe('central editor state behavior', () => {
  it('requires a selected session and accepts only absolute POSIX, drive, or UNC paths', () => {
    const store = createCentralEditorStore()
    expect(store.openFile('/work/a.ts')).toBe(false)
    expect(store.getSnapshot()).toMatchObject({ sessionId: undefined, documents: [], activePath: null, visible: false })
    store.setSession('a')
    for (const path of ['a.ts', './a.ts', 'C:a.ts', '', '/a\0.ts']) {
      expect(() => store.openFile(path)).toThrow('absolute file path')
    }
    for (const path of ['/work/a.ts', 'C:\\work\\a.ts', '\\\\server\\share\\a.ts']) {
      expect(store.openFile(path)).toBe(true)
    }
    expect(store.getSnapshot().documents).toHaveLength(3)
  })

  it('opens fixed files in order and deduplicates without replacing an existing draft or title', () => {
    const store = selectedStore()
    store.openFile('/work/a.ts', { title: 'Custom', content: 'original' })
    store.updateDraft('/work/a.ts', 'edited')
    store.openFile('/work/b.ts')
    store.openFile('/work/a.ts', { title: 'Changed', content: 'stale disk' })
    expect(store.getSnapshot()).toMatchObject({ activePath: '/work/a.ts', visible: true })
    expect(store.getSnapshot().documents).toEqual([
      { path: '/work/a.ts', generation: 1, title: 'Custom', savedContent: 'original', draft: 'edited', dirty: true },
      { path: '/work/b.ts', generation: 2, title: 'b.ts', draft: null, dirty: false },
    ])
    const before = store.getSnapshot()
    expect(store.setActivePath('/missing')).toBe(false)
    expect(store.getSnapshot()).toBe(before)
    expect(store.setActivePath('/work/b.ts')).toBe(true)
    expect(store.getSnapshot().activePath).toBe('/work/b.ts')
  })

  it('loads initial and empty content without overwriting input typed before load', () => {
    const store = selectedStore()
    store.openFile('/work/a.ts')
    store.initializeContent('/work/a.ts', '')
    expect(store.getSnapshot().documents[0]).toMatchObject({ draft: '', savedContent: '', dirty: false })
    store.openFile('/work/b.ts')
    store.updateDraft('/work/b.ts', 'early edit')
    store.initializeContent('/work/b.ts', 'disk')
    expect(store.getSnapshot().documents[1]).toMatchObject({ draft: 'early edit', savedContent: 'disk', dirty: true })
    const loaded = store.getSnapshot()
    store.initializeContent('/work/b.ts', 'stale reread')
    expect(store.getSnapshot()).toBe(loaded)
    store.updateDraft('/work/b.ts', 'disk')
    expect(store.getSnapshot().documents[1]!.dirty).toBe(false)
  })

  it('also protects pre-load input when reopening supplies the initial content', () => {
    const store = selectedStore()
    store.openFile('/work/a.ts')
    store.updateDraft('/work/a.ts', '')
    store.openFile('/work/a.ts', { content: 'disk' })
    expect(store.getSnapshot().documents[0]).toMatchObject({ draft: '', savedContent: 'disk', dirty: true })
    store.openFile('/work/a.ts', { content: 'another read' })
    expect(store.getSnapshot().documents[0]).toMatchObject({ draft: '', savedContent: 'disk', dirty: true })
  })

  it('refuses dirty closes without any mutation or notification unless force is explicitly true', () => {
    const store = selectedStore()
    store.openFile('/a', { content: 'baseline' })
    store.updateDraft('/a', 'draft')
    const listener = vi.fn()
    store.subscribe(listener)
    const before = store.getSnapshot()
    expect(store.closeFile('/a')).toBe(false)
    expect(store.closeFile('/a', { force: false })).toBe(false)
    expect(store.closeFile('/missing', { force: true })).toBe(false)
    expect(store.getSnapshot()).toBe(before)
    expect(listener).not.toHaveBeenCalled()
    expect(store.closeFile('/a', { force: true })).toBe(true)
    expect(store.getSnapshot()).toMatchObject({ documents: [], activePath: null, visible: false })
    expect(listener).toHaveBeenCalledTimes(1)
  })

  it('keeps selection when closing inactive files, then chooses the next or preceding neighbor', () => {
    const store = selectedStore()
    for (const path of ['/a', '/b', '/c', '/d']) store.openFile(path)
    store.setActivePath('/b')
    store.closeFile('/d')
    expect(store.getSnapshot().activePath).toBe('/b')
    store.closeFile('/b')
    expect(store.getSnapshot().activePath).toBe('/c')
    store.closeFile('/c')
    expect(store.getSnapshot().activePath).toBe('/a')
    store.closeFile('/a')
    expect(store.getSnapshot()).toMatchObject({ activePath: null, visible: false })
  })

  it('marks only the committed text as saved and keeps newer input dirty', () => {
    const store = selectedStore()
    store.openFile('/a', { content: 'initial' })
    store.updateDraft('/a', 'submitted')
    const submitted = store.getSnapshot().documents[0]!.draft!
    store.updateDraft('/a', 'typed while saving')
    store.markSaved('/a', submitted)
    expect(store.getSnapshot().documents[0]).toMatchObject({ savedContent: 'submitted', draft: 'typed while saving', dirty: true })
    expect(store.closeFile('/a')).toBe(false)
    store.markSaved('/a', 'typed while saving')
    expect(store.getSnapshot().documents[0]!.dirty).toBe(false)
    store.updateDraft('/a', '')
    store.markSaved('/a', '')
    expect(store.getSnapshot().documents[0]).toMatchObject({ savedContent: '', draft: '', dirty: false })
  })

  it('restores every session independently, including hidden drafts and active selection', () => {
    const store = selectedStore()
    store.openFile('/a', { content: 'session a' })
    store.openFile('/b')
    store.updateDraft('/a', 'private draft')
    store.setActivePath('/a')
    store.setVisible(false)
    const a = store.getSnapshot()
    store.setSession('b')
    expect(store.getSnapshot()).toMatchObject({ documents: [], activePath: null, visible: false })
    store.openFile('/a', { content: 'session b' })
    const b = store.getSnapshot()
    store.setSession(undefined)
    expect(store.getSnapshot().documents).toEqual([])
    store.setSession('a')
    expect(store.getSnapshot()).toBe(a)
    store.setSession('b')
    expect(store.getSnapshot()).toBe(b)
    expect(store.getSnapshot().documents[0]!.draft).toBe('session b')
    expect(createCentralEditorStore().getSnapshot().documents).toEqual([])
  })

  it('targets async load and save completions at their original background session', () => {
    const store = selectedStore()
    store.openFile('/a', { content: 'old' })
    store.updateDraft('/a', 'submitted')
    store.openFile('/loading')
    store.setSession('b')
    store.openFile('/a', { content: 'other session' })
    const b = store.getSnapshot()
    const listener = vi.fn()
    store.subscribe(listener)
    store.markSaved('/a', 'submitted', 'a')
    store.initializeContent('/loading', 'loaded', 'a')
    store.openFile('/background', {}, 'a')
    expect(store.getSnapshot()).toBe(b)
    expect(listener).not.toHaveBeenCalled()
    expect(store.getSessionSnapshot('a')!.documents[0]).toMatchObject({ draft: 'submitted', dirty: false })
    store.setSession('a')
    expect(store.getSnapshot().documents[1]!.draft).toBe('loaded')
    expect(store.getSnapshot().activePath).toBe('/background')
  })

  it('has stable bound methods and immutable stable snapshots, notifying only on selected-session changes', () => {
    const store = selectedStore()
    const { getSnapshot, subscribe } = store
    expect(getSnapshot).toBe(store.getSnapshot)
    expect(subscribe).toBe(store.subscribe)
    const listener = vi.fn(() => expect(getSnapshot()).toBe(store.getSnapshot()))
    const unsubscribe = subscribe(listener)
    const empty = getSnapshot()
    store.setSession('a')
    store.setVisible(false)
    store.updateDraft('/missing', 'ignored')
    store.markSaved('/missing', 'ignored')
    store.initializeContent('/missing', 'ignored')
    expect(getSnapshot()).toBe(empty)
    expect(listener).not.toHaveBeenCalled()
    store.openFile('/a', { content: 'same' })
    const opened = getSnapshot()
    expect(listener).toHaveBeenCalledTimes(1)
    store.openFile('/a')
    store.setActivePath('/a')
    store.setVisible(true)
    store.updateDraft('/a', 'same')
    store.markSaved('/a', 'same')
    store.initializeContent('/a', 'same')
    expect(getSnapshot()).toBe(opened)
    expect(listener).toHaveBeenCalledTimes(1)
    expect(Object.isFrozen(opened)).toBe(true)
    expect(Object.isFrozen(opened.documents)).toBe(true)
    expect(Object.isFrozen(opened.documents[0])).toBe(true)
    store.updateDraft('/a', 'changed')
    expect(getSnapshot()).not.toBe(opened)
    expect(opened.documents[0]!.draft).toBe('same')
    expect(listener).toHaveBeenCalledTimes(2)
    unsubscribe()
    unsubscribe()
    store.setVisible(false)
    expect(listener).toHaveBeenCalledTimes(2)
    expect(store.getSnapshot().documents[0]!.draft).toBe('changed')
  })
})
