/**
 * Tests for tools/convert-vscode-icon-theme.mjs — the official VSIX → TS
 * icon-theme converter. Fixtures are synthetic extracted-VSIX directories
 * in a temp dir (deterministic, no network/VSIX dependency); the REAL
 * material-icon-theme 5.38.1 conversion was validated manually end-to-end
 * (1251 definitions / 12820 map entries / 1870 KB → 374 KB gzip, engine
 * resolves real rows).
 */
import { describe, expect, it, afterEach } from 'vitest'
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { convertIconTheme } from '../tools/convert-vscode-icon-theme.mjs'
import { buildIconThemeIndex, matchFileIcon, type IconThemeDocument } from '../src/client/icon-theme.ts'

const cleaned: string[] = []
afterEach(() => { for (const dir of cleaned.splice(0)) rmSync(dir, { recursive: true, force: true }) })

const SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="#fff" d="M0 0h24v24H0z"/></svg>'

/** Build a synthetic extracted-VSIX directory; returns its path. */
function fixtureDir(overrides: { theme?: Record<string, unknown> } = {}): string {
  const dir = mkdtempSync(join(tmpdir(), 'icon-theme-convert-'))
  cleaned.push(dir)
  const ext = join(dir, 'extension')
  mkdirSync(join(ext, 'dist'), { recursive: true })
  mkdirSync(join(ext, 'icons'), { recursive: true })
  writeFileSync(join(ext, 'package.json'), JSON.stringify({
    name: 'fake-theme', version: '1.2.3',
    contributes: { iconThemes: [{ id: 'fake', label: 'Fake Theme', path: './dist/theme.json' }] },
  }))
  writeFileFile(join(ext, 'LICENSE.txt'), 'MIT fake')
  writeFileSync(join(ext, 'icons', 'file.svg'), SVG)
  writeFileSync(join(ext, 'icons', 'font.woff2'), Buffer.from([0, 1, 2, 3]))
  const theme = overrides.theme ?? {
    iconDefinitions: { file: { iconPath: './../icons/file.svg' } },
    fileNames: { 'x.json': 'file' },
    file: 'file',
    // Sections the sidebar ignores — the converter must DROP these.
    languageIds: { json: 'file' },
    light: { fileExtensions: { blinked: 'file' } },
    hidesExplorerArrows: true,
  }
  writeFileSync(join(ext, 'dist', 'theme.json'), JSON.stringify(theme))
  return dir
}

/** Write a text file (small helper for the fixture builder). */
function writeFileFile(path: string, text: string): void {
  writeFileSync(path, text)
}

/** Evaluate the emitted TS module (strip import/annotation) into the doc. */
function evalDoc(ts: string): IconThemeDocument {
  const body = ts
    .replace(/^import type .*$/m, '')
    .replace(/^export const iconTheme: IconThemeDocument = /m, 'const iconTheme = ')
  const fn = new Function(`${body}; return iconTheme`) as () => IconThemeDocument
  return fn()
}

describe('convert-vscode-icon-theme.mjs', () => {
  it('rewrites assets to base64 data URLs and keeps the normalized document', () => {
    const dir = fixtureDir()
    const { ts, stats } = convertIconTheme({ dir })
    // Header carries the source identity + the license verbatim.
    expect(ts).toContain('GENERATED by tools/convert-vscode-icon-theme.mjs')
    expect(ts).toContain('fake-theme 1.2.3')
    expect(ts).toContain('MIT fake')
    // The iconPath became a base64 data URL of the REAL svg bytes.
    expect(ts).toContain(`data:image/svg+xml;base64,${Buffer.from(SVG).toString('base64')}`)
    // Ignored sections dropped; kept sections + defaults present.
    expect(ts).not.toContain('languageIds')
    expect(ts).not.toContain('hidesExplorerArrows')
    expect(ts).not.toContain('light')
    expect(ts).toContain('"fileNames"')
    expect(stats.definitions).toBe(1)
    // The emitted module is a valid IconThemeDocument the ENGINE consumes.
    const doc = evalDoc(ts)
    const index = buildIconThemeIndex(doc, 'fake')
    const ref = matchFileIcon(index, { name: 'x.json', isDir: false })
    expect(ref?.kind).toBe('svg-image')
    const url = ref?.kind === 'svg-image' ? ref.url : undefined
    expect(url).toBe(`data:image/svg+xml;base64,${Buffer.from(SVG).toString('base64')}`)
  })

  it('always carries the default fallback fields, empty maps stay {}', () => {
    const dir = fixtureDir()
    const { ts } = convertIconTheme({ dir })
    const doc = evalDoc(ts)
    expect(doc.file).toBe('file')
    expect(doc.folder).toBeUndefined() // absent in the source → absent here
    expect(doc.rootFolderNames).toEqual({}) // absent → explicit empty map
    expect(doc.folderNames).toEqual({})
  })

  it('converts font themes to data:font URLs with the glyph metadata', () => {
    const dir = fixtureDir({
      theme: {
        iconDefinitions: {
          f: { fontCharacter: '\\ue001', fontPath: './../icons/font.woff2', fontSize: '150%' },
        },
        fileExtensions: { js: 'f' },
      },
    })
    const { ts } = convertIconTheme({ dir })
    expect(ts).toContain('data:font/woff2;base64,AAECAw==')
    const doc = evalDoc(ts)
    expect(doc.iconDefinitions.f?.fontCharacter).toBe('\\ue001')
    const index = buildIconThemeIndex(doc, 'fake')
    const font = matchFileIcon(index, { name: 'a.js', isDir: false })
    expect(font?.kind).toBe('font')
  })

  it('fails HARD on a missing referenced asset (strict) and degrades with warnings under --no-strict', () => {
    const dir = fixtureDir({
      theme: {
        iconDefinitions: {
          ok: { iconPath: './../icons/file.svg' },
          broken: { iconPath: './../icons/missing.svg' },
        },
        fileNames: { 'a.json': 'ok', 'b.json': 'broken' },
        file: 'ok',
      },
    })
    expect(() => convertIconTheme({ dir })).toThrow(/missing iconPath file/)
    const { ts, warnings, stats } = convertIconTheme({ dir, strictMissing: false })
    expect(warnings).toHaveLength(1)
    expect(warnings[0]).toContain('"broken"')
    expect(stats.definitions).toBe(1)
    expect(ts).not.toContain('missing.svg')
    // The dangling map ref falls through to the default at runtime.
    const doc = evalDoc(ts)
    const index = buildIconThemeIndex(doc, 'fake')
    expect(matchFileIcon(index, { name: 'a.json', isDir: false })).toBeDefined()
    expect(matchFileIcon(index, { name: 'b.json', isDir: false })).toBeDefined()
  })

  it('rejects unsupported asset types and asset-less definitions', () => {
    const dir = fixtureDir()
    writeFileSync(join(dir, 'extension', 'icons', 'app.exe'), Buffer.from('MZ'))
    // The theme JSON must reference the now-existing file for the MIME
    // check to be the failure (a missing file is the strict error path).
    const themePath = join(dir, 'extension', 'dist', 'theme.json')
    const theme = JSON.parse(readFileSync(themePath, 'utf8')) as Record<string, unknown>
    theme.iconDefinitions = { exe: { iconPath: './../icons/app.exe' } }
    writeFileSync(themePath, JSON.stringify(theme))
    expect(() => convertIconTheme({ dir })).toThrow(/unsupported asset type/)
    const dir2 = fixtureDir({
      theme: { iconDefinitions: { empty: {} } },
    })
    expect(() => convertIconTheme({ dir: dir2 })).toThrow(/needs iconPath or fontCharacter/)
  })

  it('honors the export name option', () => {
    const dir = fixtureDir()
    const { ts } = convertIconTheme({ dir, exportName: 'materialTheme' })
    expect(ts).toContain('export const materialTheme: IconThemeDocument =')
  })
})