/**
 * Interception of the chat's produced-files row: the turn-tail chain entry
 * that replaces ui-deliverables' row when the closing turn produced files.
 * The takeover looks identical (same chip row); the chips open the file in
 * the sidebar instead of the host OS. Priority -1 runs before the default-0
 * deliverables entry; when nothing was produced the selector returns null
 * and the original row renders unchanged.
 */
import { useCallback, useSyncExternalStore } from 'react'
import { IconCodeOutline16 } from '@deepseek-ai/dsh-client-ui-primitives'
import type { Context } from '../context-types.ts'
import { firstLeaf, paneInArea, revealPaths, setSideBarOpen, togglePanel, type SidebarStore, type WorkspaceArea } from './state.ts'
import { api } from './api.ts'
import { IconDiffOutline16, IconScrollHOutline16, IconWrapOutline16 } from './icons.tsx'
import { t } from './locales.ts'
import { flipBooleanPref } from './prefs.ts'
import { resolveSidebarPath, selectProducedFiles } from './produced-files.ts'
import { wrapOpenPath } from './openpath-intercept.ts'
import css from './sidebar.module.css'

/**
 * Open a file in the sidebar's editor (used by the intercepted row and the
 * explorer). A DIRECTORY must not open an editor tab — the host `fs.read`
 * rejects it (`"..." is a directory`) and the tab would only show an error.
 * The path is probed with `fs.tree` (it lists a directory and fails on a
 * file/absent path): on a directory the vscode explorer drawer is expanded
 * instead (a no-op in the docked layout — the click lands on the file tree),
 * otherwise the file opens as before.
 *
 * `area` pins the landing panel for TREE-originated opens: the
 * open must land in the panel the tree lives in ("click in the right → open
 * in the right"), never wherever the global `activePane` last pointed — a
 * prior interaction on the bottom panel would otherwise swallow the open
 * (the vscode Side Bar's tree lives outside any workbench pane, so no pane
 * pointerdown focuses it). Dispatching `activePane` to the area's pane is
 * the same focus the docked tree's own pointerdown applies; the openTab
 * auto-expand then opens the hosting panel. Chat-side opens (produced-files
 * row, open-path interception) pass no area and keep the activePane landing.
 */
export function openSidebarFile(ctx: Context, store: SidebarStore, sessionId: string, path: string, area?: WorkspaceArea): void {
  const summary = ctx.sessions.list.getSnapshot().byId[sessionId]
  const absolute = resolveSidebarPath(summary?.cwd, path)
  const at = Math.max(absolute.lastIndexOf('/'), absolute.lastIndexOf('\\'))
  const title = at === -1 ? absolute : absolute.slice(at + 1)
const open = (): void => {
    if (area !== undefined) {
      store.reduce(state => {
        const target = paneInArea(state, area)
        return state.activePane === target ? state : { ...state, activePane: target }
      })
    }
    // Route through the sidebar service so the editor descriptor's dedupeKey
    // (per-path) applies; the id is path-derived so multiple editors coexist.
    ctx.betterSidebar?.openTab({ type: 'editor', title, path: absolute, id: `editor:${absolute}` })
  }
  api.fsTree({ sessionId, cwd: summary?.cwd }, absolute).then(() => {
    // A directory: no editor tab. In the vscode layout the explorer drawer
    // expands so the user lands on the tree; docked is a no-op.
    if (store.getPrefs().sidebarLayout === 'vscode') {
      store.reduce(s => setSideBarOpen(s, true))
    }
  }).catch(() => {
    // A file (or absent path — the editor surfaces the read error there).
    open()
  })
}

/**
 * The produced files the turn-tail selector last matched for the visible
 * session. The "Show in folder" gesture carries no file path of its own
 * (`'.'`), so the reveal highlights exactly these rows when available.
 */
let lastProduced: readonly string[] = []

/** Deterministic review-tab id derived from the RESOLVED produced paths: the
 *  same produced set re-focuses its review tab (per-change dedupe), while a
 *  NEW turn's produced set opens a fresh review — the previous one stays open
 *  for comparison instead of silently changing content. */
function reviewTabId(paths: readonly string[]): string {
  let hash = 5381
  for (const path of paths) {
    for (let i = 0; i < path.length; i += 1) {
      hash = ((hash << 5) + hash + path.charCodeAt(i)) >>> 0
    }
  }
  return `diff:review:${hash.toString(36)}`
}

/**
 * Open the produced-files REVIEW: one diff tab carrying the combined
 * uncommitted diff of exactly the produced files — the "important changes" of
 * this turn's git diff (DiffView expands source files and folds tests/docs/
 * generated by default), so the user can approve the change in a single
 * glance. The panel expands and the landing pane pins to the right tree's
 * first leaf (the revealInExplorer rule) so the surface lands in sight.
 */
export function openReviewSurface(
  ctx: Context,
  store: SidebarStore,
  sessionId: string,
  files: readonly string[],
): void {
  const summary = ctx.sessions.list.getSnapshot().byId[sessionId]
  const cwd = summary?.cwd
  const paths = files.map(path => resolveSidebarPath(cwd, path))
  if (paths.length === 0) return
  store.reduce(s => (s.panelOpen ? s : togglePanel(s)))
  store.reduce(s => ({ ...s, activePane: firstLeaf(s.splits).id }))
  ctx.get('betterSidebar')?.openTab({
    type: 'diff',
    title: `${t('review')} · ${paths.length}`,
    id: reviewTabId(paths),
    diff: { kind: 'review', paths },
  })
}

/**
 * Flip the produced-files row between auto-wrap and single-line horizontal
 * scroll (optimistic + persisted — see {@link flipBooleanPref}).
 */
export function toggleProducedWrap(store: SidebarStore): void {
  flipBooleanPref(store, 'producedFilesWrap')
}

/**
 * Reveal the produced files in the sidebar explorer: expand their parent
 * directories, highlight the rows, and focus the explorer tab (expanding the
 * hosting panel when it is collapsed). Unknown files fall back to revealing
 * the workspace root itself.
 */
export function revealInExplorer(
  ctx: Context,
  store: SidebarStore,
  sessionId: string,
  files: readonly string[],
): void {
  const summary = ctx.sessions.list.getSnapshot().byId[sessionId]
  const cwd = summary?.cwd
  // Deliverables report paths as-is (often relative to the session cwd), but
  // the explorer tree and revealPaths work on absolute paths — resolve every
  // target so the ancestors expand and the row actually matches.
  const targets = files.length > 0
    ? files.map(path => resolveSidebarPath(cwd, path))
    : cwd === undefined ? [] : [cwd]
  store.reduce(state => revealPaths(state, cwd, targets))
  // A type-only open never auto-expands the panel (only content opens do,
  // see service.openTab) — so a reveal opens the panel itself when it is
  // collapsed, exactly like the subagent auto-open flows, or the highlight
  // would be set on an invisible panel.
  store.reduce(s => (s.panelOpen ? s : togglePanel(s)))
  // Pin the landing to the right panel: the files window must appear where
  // the panel just expanded, not in a bottom-panel pane the user last
  // touched.
  store.reduce(s => ({ ...s, activePane: firstLeaf(s.splits).id }))
  // Focus the single-instance editor home tab (the files window) where the
  // reveal highlight renders. Read via ctx.get like every other internal
  // consumer (#357): the provider is not on this fiber chain, so a direct
  // ctx.betterSidebar read can throw before optional chaining applies.
  ctx.get('betterSidebar')?.openTab({ type: 'editor', title: t('files') })
}

/** The intercepted produced-files row (visual twin of the deliverables chips). */
export function SidebarProducedFiles(props: {
  matched: readonly string[]
  openInSidebar: (path: string) => void
  /** Reveal the produced files in the explorer ("Show in folder" twin). */
  onShowInFolder: (files: readonly string[]) => void
  /** Open the combined diff review of the produced files (the review button). */
  onReview: (files: readonly string[]) => void
  /** Flip the row between auto-wrap and single-line horizontal scroll. */
  onToggleWrap: () => void
  /** The sidebar store: the row subscribes for the live wrap pref. */
  store: SidebarStore
}) {
  const { matched, openInSidebar, onShowInFolder, onReview, onToggleWrap, store } = props
  // The row re-renders itself when the wrap pref changes (a store write from
  // the toggle button or the settings page); the chat chain render alone
  // would never see the update until the next conversation event.
  const prefs = useSyncExternalStore(
    useCallback((callback: () => void) => store.subscribe(callback), [store]),
    // getSnapshot MUST return a stable reference (useSyncExternalStore compares
    // with Object.is between renders; `getPrefs()` copies every call and would
    // force an endless re-render loop). The snapshot's prefs object is stable
    // until a setPrefs replaces it.
    useCallback(() => store.getSnapshot().prefs, [store]),
  )
  const wrap = prefs.producedFilesWrap !== false
  const shown = matched.slice(0, 6)
  const hidden = matched.length - shown.length
  return (
    <div className={wrap ? css.producedRow : `${css.producedRow} ${css.producedRowNowrap}`}>
      <span className={css.producedLabel}>{t('produced')}</span>
      <button
        type="button"
        className={css.producedWrapToggle}
        aria-pressed={wrap}
        aria-label={wrap ? t('producedWrapOff') : t('producedWrapOn')}
        title={wrap ? t('producedWrapOff') : t('producedWrapOn')}
        onClick={onToggleWrap}
      >
        {wrap ? <IconWrapOutline16 size={12} /> : <IconScrollHOutline16 size={12} />}
      </button>
      {shown.map(path => {
        const at = Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\'))
        const name = at === -1 ? path : path.slice(at + 1)
        return (
          <button
            key={path}
            type="button"
            className={css.producedChip}
            title={path}
            onClick={() => { openInSidebar(path) }}
          >
            <IconCodeOutline16 size={12} />
            <span>{name}</span>
          </button>
        )
      })}
      {hidden > 0 && <span className={css.producedMore}>+{hidden}</span>}
      {hidden > 0 && (
        <button
          type="button"
          className={css.producedMore}
          style={{ cursor: 'pointer', textDecoration: 'underline', textUnderlineOffset: 2 }}
          onClick={() => { onShowInFolder(matched) }}
        >
          {t('showInFolder')}
        </button>
      )}
      <button
        type="button"
        className={css.producedReview}
        title={t('review')}
        onClick={() => { onReview(matched) }}
      >
        <IconDiffOutline16 size={12} />
        <span>{t('review')}</span>
      </button>
    </div>
  )
}

/**
 * Register the turn-tail interception (returns the disposer).
 *
 * The slot is a CHILD slot the host's ui-conversation declares in its
 * `conversation.chat.node` children table (kind: chain, scope: session).
 * Registering it directly races the declaration — the ui-slots core's
 * load-time validation throws "not declared (a parent entry's children
 * table must declare it)" when the parent entry is not on the ledger yet.
 * slots.inject waits for the declaration: the callback runs synchronously
 * when the slot is already declared, otherwise it runs inside the declaring
 * register() call once the declaration commits; declaration collapse
 * disposes the entry and a later declaration re-registers it. This mirrors
 * @deepseek-ai/dsh-client-ui-deliverables' registration of the same slot.
 */
export function registerTurnTailInterception(ctx: Context, store: SidebarStore): () => void {
  return ctx.slots.inject('conversation.chat.turnTail', () => ctx.slots.register({
    name: 'conversation.chat.turnTail',
    // Decline the takeover while the editor tab type is disabled in the side
    // card settings: the produced-files row falls back to the default
    // deliverables behavior instead of offering chips that cannot open. Also
    // while the sidebar is externally disabled (aionui-panel chosen).
    select: (owner) => {
      if (store.getSuspended()) return null
      if (store.getPrefs().tabsEnabled['editor'] === false) return null
      const matched = selectProducedFiles(owner)
      if (matched !== null) lastProduced = matched
      return matched
    },
    priority: -1,
    registrant: 'dsh-better-sidebar',
    inject: (sessionId: string) => ({
      openInSidebar: (path: string) => { openSidebarFile(ctx, store, sessionId, path) },
      onShowInFolder: (files: readonly string[]) => { revealInExplorer(ctx, store, sessionId, files) },
      onReview: (files: readonly string[]) => { openReviewSurface(ctx, store, sessionId, files) },
      onToggleWrap: () => { toggleProducedWrap(store) },
      store,
    }),
  }, SidebarProducedFiles))
}

/**
 * Register the chat file-open interception: wraps `ctx.workspaces.openPath`
 * — the single funnel every chat-side file open goes through (tool-row path
 * links, the produced-files row, prose mentions) — so opens land in the
 * sidebar editor instead of the Host OS. The folder-reveal gesture ("Show in
 * folder" passes `'.'`) is the one exception: it is routed to the explorer.
 * Gated by BOTH the `interceptOpenPath` pref and the editor tab's enable
 * switch; declined opens fall through to the original method. Returns the
 * disposer restoring the original (HMR-safe).
 */
export function registerOpenPathInterception(ctx: Context, store: SidebarStore): () => void {
  return wrapOpenPath(ctx.workspaces, {
    takeoverEnabled: () => !store.getSuspended()
      && store.getPrefs().interceptOpenPath !== false
      && store.getPrefs().tabsEnabled['editor'] !== false,
    currentSessionId: () => ctx.sessions.list.getSnapshot().current,
    openInSidebar: (path, sessionId) => { openSidebarFile(ctx, store, sessionId, path) },
    revealInExplorer: (_path, sessionId) => { revealInExplorer(ctx, store, sessionId, lastProduced) },
  })
}
